// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mY3BBUAHZJY6Tsok2n7_4t3IhYOKsaA',
    appId: '1:134976989222:web:7a911f8497a9b635221ee7',
    messagingSenderId: '134976989222',
    projectId: 'library-project-af8ca',
    authDomain: 'library-project-af8ca.firebaseapp.com',
    storageBucket: 'library-project-af8ca.firebasestorage.app',
    measurementId: 'G-NJ9R3E8L0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIl-hOkfJ20-K2p8F09XKZ544pkFwF3e4',
    appId: '1:134976989222:android:a010e3245eb2d244221ee7',
    messagingSenderId: '134976989222',
    projectId: 'library-project-af8ca',
    storageBucket: 'library-project-af8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAFWEuO_Z08FoU_96Me77W4rp3sidg7b8',
    appId: '1:134976989222:ios:0d511a256ac4dd1f221ee7',
    messagingSenderId: '134976989222',
    projectId: 'library-project-af8ca',
    storageBucket: 'library-project-af8ca.firebasestorage.app',
    iosBundleId: 'com.example.reGiveFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAFWEuO_Z08FoU_96Me77W4rp3sidg7b8',
    appId: '1:134976989222:ios:0d511a256ac4dd1f221ee7',
    messagingSenderId: '134976989222',
    projectId: 'library-project-af8ca',
    storageBucket: 'library-project-af8ca.firebasestorage.app',
    iosBundleId: 'com.example.reGiveFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-mY3BBUAHZJY6Tsok2n7_4t3IhYOKsaA',
    appId: '1:134976989222:web:7986c80bddc5c36d221ee7',
    messagingSenderId: '134976989222',
    projectId: 'library-project-af8ca',
    authDomain: 'library-project-af8ca.firebaseapp.com',
    storageBucket: 'library-project-af8ca.firebasestorage.app',
    measurementId: 'G-WZXK2M8SFN',
  );
}
